### ISSUE TITLE
libcec 4.0.3 python client: "NameError: name 'raw_input' is not defined"

### ISSUE THREAD

**Issue by fkierbye** [Pulse-Eight/libcec#440]
I have an issue with python client on libcec version 4.0.3 built from source.
Ubuntu 18.04. Python 3.6.7.

```
$ ./pyCecClient.py 
<module 'cec' from '/usr/local/lib/python3.6/dist-packages/cec.py'>
libCEC version 4.0.3 loaded: git revision: <unknown>, compiled on Fri Nov 16 09:32:51 UTC 2018 by donald@duck on Linux 4.15.0-40-generic (x86_64), features: P8_USB, DRM, P8_detect, randr
NOTICE:  [135]     connection opened
found a CEC adapter:
port:     /dev/ttyACM0
vendor:   0x2548
product:  0x1002
NOTICE:  [1154]     connection opened
TRAFFIC: [1154]     << f0
TRAFFIC: [1191]     << f0
NOTICE:  [1227]     registering new CEC client - v4.0.3
TRAFFIC: [1227]     << 11
TRAFFIC: [1259]     << 11
NOTICE:  [1305]     setting HDMI port to 1 on device TV (0)
TRAFFIC: [1305]     << 10
TRAFFIC: [1338]     << 10
TRAFFIC: [1370]     << 1f:84:10:00:01
NOTICE:  [1555]     CEC client registered: libCEC version = 4.0.3, client version = 4.0.3, firmware version = 7, firmware build date: Wed Apr 13 10:36:11 2016 +0000, logical address(es) = Recorder 1 (1) , base device: TV (0), HDMI port number: 1, physical address: 1.0.0.0, git revision: <unknown>, compiled on Fri Nov 16 09:32:51 UTC 2018 by donald@duck on Linux 4.15.0-40-generic (x86_64), features: P8_USB, DRM, P8_detect, randr
TRAFFIC: [1555]     << 10
TRAFFIC: [1586]     << 10
TRAFFIC: [1624]     << 10
TRAFFIC: [1655]     << 10
connection opened
Traceback (most recent call last):
  File "./pyCecClient.py", line 219, in <module>
    lib.InitLibCec()
  File "./pyCecClient.py", line 85, in InitLibCec
    self.MainLoop()
  File "./pyCecClient.py", line 152, in MainLoop
    command = raw_input("Enter command:").lower()
NameError: name 'raw_input' is not defined
```

I solved this by changing line 152 from
```      command = raw_input("Enter command:").lower()```
to:
```      command = input("Enter command:").lower()```

See also:
https://stackoverflow.com/questions/954834/how-do-i-use-raw-input-in-python-3

**Comment by opdenkamp** [comment]
fixed in 81c4bc5e455e776f2b0b149b41f5a1c349a57359
