### ISSUE TITLE
Unhandled exceptions

### ISSUE THREAD

**Issue by GromitD90** [Pulse-Eight/libcec#461]
I am writing my own C# program using the latest version of LibCecSharp.dll. I used the source of CecSharpTester as a starting point and have hit 2 issues of unhandled exceptions, both of which can be reproduced when using CecSharpTester itself.

Issue 1.
I open my connection to the adapter with monitor mode set to ON. This prevents the TV from being turned ON when the connection is made. When the TV is turned ON manually I detect that and set Monitor mode to OFF so that I can get the physical address of the adapter. Having got that address I then want to turn monitor mode back on which I do by calling Lib.SwitchMonitoring(true) that is when I get my first unhandled exception 

Unhandled Exception: System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at CecSharp.LibCecSharp.SwitchMonitoring(Boolean enable)
   at CecSharpClient.CecSharpClient.MainLoop()
   at CecSharpClient.CecSharpClient.Main(String[] args)

For the time being I just leave Monitoring mode OFF (once I've turned it OFF) but this introduces a second problem.
Issue 2.
As expected, if my PC goes to sleep then when it wakes up I am able to capture the fact it is disconnected and reetablish the connection. If I do this prior to turning monitor mode OFF programatically the connection is reestablished and all goes on as normal. However once monitor mode has been turned OFF the first attempt to reestablish connection fails with an unhandled exception on the Lib.Close() call.

Unhandled Exception: System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at CecSharp.LibCecSharp.Close()
   at CecSharpClient.CecSharpClient.MainLoop()
   at CecSharpClient.CecSharpClient.Main(String[] args)

I can reproduce these same exceptions using CecSharpTester and the errors shown above are from that .exe. I am attaching the console output so that you can see the sequence of keyboard entered commands that cause the errors.

If you have any suggestions on how to work around these problems I would be grateful.
Thanks in advance
[cecsharptester exception.txt](https://github.com/Pulse-Eight/libcec/files/3369008/cecsharptester.exception.txt)

**Comment by opdenkamp** [comment]
First off, apologies that this was auto-closed as stale before it was properly triaged — it's a genuine crash and shouldn't have been closed.

Both `AccessViolationException`s (in `SwitchMonitoring` and in `Close`) come from the same root cause in the core library, which also underlies #505 (native `SIGSEGV` toggling monitor mode on → off → on). The `LibCecSharp` wrapper is just where it surfaces on Windows.

**What was happening:** `CCECProcessor::RegisterClient(CCECClient*)` reused the existing `shared_ptr` for a client only if it was still in the processor's client map. Enabling monitoring mode clears that map (`UnregisterClients()`), so disabling monitoring re-registered the client through `RegisterClient(CECClientPtr(client))`, which **constructed a brand-new, independent `shared_ptr` control block from the raw pointer**. The client was then owned by two unrelated control blocks — the one `CLibCEC` still holds, plus the new one in the processor map. The next time monitoring was enabled, `m_clients.erase()` dropped the processor's control block to zero and **deleted the client while `CLibCEC` was still using it**, so the following call (`SwitchMonitoring`, `Close`, …) touched freed memory.

This also explains @HomerSp's observation in #505 that removing the `m_clients.erase()` line made it go away — that just stopped the premature delete, masking the double-ownership rather than fixing it.

Fixed in 65c04a7: the re-register path now reuses the `shared_ptr` that `CLibCEC` still owns instead of wrapping the raw `this`, so there's only ever one control block per client. This lands in the next release.
