### ISSUE TITLE
Cannot import cec Python, unexpected reloc type 0x03

### ISSUE THREAD

**Issue by dougppaz** [Pulse-Eight/libcec#466]
I trying import cec "cec.py" but this error is raised.

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "cec.py", line 21, in <module>
    _cec = swig_import_helper()
  File "cec.py", line 20, in swig_import_helper
    return importlib.import_module('_cec')
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: ./_cec.so: unexpected reloc type 0x03
```

```
$ uname -a
Linux osmc 4.14.78-4-osmc #1 SMP PREEMPT Wed Dec 12 17:58:11 UTC 2018 armv7l GNU/Linux
```

**Comment by opdenkamp** [comment]
this is a build issue, incompatible libcec.so and python wrapper. probably because one of the two got upgraded and the other one didn't
