### ISSUE TITLE
Python module not working on windows

### ISSUE THREAD

**Issue by ja-ha** [Pulse-Eight/libcec#649]
Hi, I'm trying to get this running on windows with python3.12.
It seems to import the correct module (provided by the libcec installer) but for some reason I can't actually use it.

```powershell
PS C:\Program Files (x86)\Pulse-Eight\USB-CEC Adapter\python> python .\pyCecClient.py
<module 'cec' from 'C:\\Program Files (x86)\\Pulse-Eight\\USB-CEC Adapter\\python\\cec\\__init__.py'>
Traceback (most recent call last):
  File "C:\Program Files (x86)\Pulse-Eight\USB-CEC Adapter\python\pyCecClient.py", line 38, in <module>
    class pyCecClient:
  File "C:\Program Files (x86)\Pulse-Eight\USB-CEC Adapter\python\pyCecClient.py", line 39, in pyCecClient
    cecconfig = cec.libcec_configuration()
                ^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'cec' has no attribute 'libcec_configuration'
```

I have verified that there are no [other libcec packages](https://pypi.org/project/cec/) installed.

What am I missing here?

**Comment by opdenkamp** [comment]
fixed in libCEC 7.0.0
